### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Bondok6** [Bondok6/taste-food#21]
# Hi There 👋

<hr>

## Thanks for taking the time to review our project

- #### [Kanban Board Link](https://github.com/Bondok6/taste-food/projects/1)
- #### Note: Our team consists of two member @andres-condezo , @Bondok6

**Comment by uwadonat** [comment]
Hi **@Team**, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
