### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by gdumani** [Bondok6/taste-food#29]
Good work, clever solutions

**Comment by andres-condezo** [comment]
Hi @Bondok6 , 
 
## Highlights
- You have a neat and clean code as always 🟢 

![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!

**Comment by Leboroz** [comment]
Hello @Bondok6 👋  great code so far

all I could say is that if you use .then instead of async-await your code would look a bit cleaner.

**Comment by Bondok6** [comment]
## Thanks, @Leboroz @gdumani @andres-condezo for the review 🙏
